/// Flutter icons CustomIcons
/// Copyright (C) 2023 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  CustomIcons
///      fonts:
///       - asset: fonts/CustomIcons.ttf
///
/// 
/// * Iconic, Copyright (C) 2012 by P.J. Onori
///         Author:    P.J. Onori
///         License:   SIL (http://scripts.sil.org/OFL)
///         Homepage:  http://somerandomdude.com/work/iconic/
/// * Font Awesome 5, Copyright (C) 2016 by Dave Gandy
///         Author:    Dave Gandy
///         License:   SIL (https://github.com/FortAwesome/Font-Awesome/blob/master/LICENSE.txt)
///         Homepage:  http://fortawesome.github.com/Font-Awesome/
///
import 'package:flutter/widgets.dart';

class CustomIcons {
  CustomIcons._();

  static const _kFontFam = 'CustomIcons';
  static const String? _kFontPkg = null;

  static const IconData play = IconData(0xe800, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData step_backward = IconData(0xf048, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData fast_backward = IconData(0xf049, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData backward = IconData(0xf04a, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData play_1 = IconData(0xf04b, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData pause = IconData(0xf04c, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData stop = IconData(0xf04d, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData forward = IconData(0xf04e, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData fast_forward = IconData(0xf050, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData step_forward = IconData(0xf051, fontFamily: _kFontFam, fontPackage: _kFontPkg);
}
